### ISSUE TITLE
Sudo access not working because of hard coded value

### ISSUE THREAD

**Issue by daydr3am3r** [Keyfactor/pem-pkcs12-remote-orchestrator#20]
It looks like there’s a logic bug in the PEM SSH orchestrator:

I noticed that on https://github.com/Keyfactor/pem-pkcs12-remote-orchestrator/blob/main/PEMStoreSSH/RemoteHandlers/SSHHandler.cs
line 192, sudo is hard coded to be disabled when the orchestrator tries to create the certificate files.

```
      public override void CreateEmptyStoreFile(string path)
        {
            RunCommand($"touch {path}", null, false, null);
            //using sudo will create as root. set useSudo to false 
            //to ensure ownership is with the credentials configued in the platform
        }
```

However, this means that the user performing the sudo commands might not be able to create the file
as it doesn’t have access to that path:

```
[user@server ~]$ touch /etc/ssl/certs/certificate.crt
touch: cannot touch ‘/etc/ssl/certs/certificate.crt’: Permission denied
[user@server ~]$
```

An idea (not necessarily the best one) if we want to maintain the original owner is to store the acting user
in a variable and modify the permissions after file creation, or create the file using another function or command
which allows specifying the user.

**Comment by doebrowsk** [comment]
Thanks for creating this issue @daydr3am3r - I am fixing this with a patch release in both this repository (for the KF 9 Universal Orchestrator) and will get a patch out for the original Windows Orchestrator repo (versions < 2 of this project) now found @ https://github.com/Keyfactor/pem-pkcs12-remote-windowsorchestrator
